# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [aelf-docs-dev, aefinder-docs-dev, tomorrowdao-docs-dev]
    environment: 
      name: ${{ matrix.environment }}
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm install

      - name: create env file
        run: |
          touch .env
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env
          echo SPACE_ID=${{ vars.SPACE_ID }} >> .env
          echo NEXT_PUBLIC_SITE_URL=${{ vars.SITE_URL }} >> .env
          echo NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ vars.CLOUDINARY_CLOUD_NAME }} >> .env

      - run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ matrix.environment }}-{{date 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_DISPATCH }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'poc-aaa',
              repo: 'devops',
              workflow_id: 'docs-cms.yaml',
              ref: 'main',
              inputs: {
                appName: '${{ matrix.environment }}',
                commit_sha: '${{ steps.meta.outputs.version }}',
              }
            })